![data-x](http://oi64.tinypic.com/o858n4.jpg)

___

# Homework 03


## Name: Derek Topper

## Student ID: 26861675

## Note: Please print the output of each question in a new cell below your code



## Numpy Introduction


__1a) Create two numpy arrays (a and b). a should be all integers between 25-34 (inclusive), and b should be ten evenly spaced numbers between 1-6. Print all the results below and store them seperately:__


i) Cube (i.e. raise to the power of 3) all the elements in both arrays (element-wise)  
ii)  Add both the cubed arrays (e.g., [1,2] + [3,4] = [4,6])  
iii)  Sum the elements with even indices of the added array.  
iv)  Take the square root of the added array (element-wise square root)




In [1]:
# your code here
import numpy as np
a = np.arange(25,35)
print("a = ", a)
b = np.arange(1, 6, .5)
print("b = ", b)

a =  [25 26 27 28 29 30 31 32 33 34]
b =  [1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5]


In [2]:
a = a**3
print("i.a) ", a)
b = b**3
print("i.b) ", b)
c = a + b
print("ii) ", c)
d = np.arange(1, 10, 2)
e = sum(c[d])
print("iii) ", e)
f = np.sqrt(c)
print("iv) ", f)

i.a)  [15625 17576 19683 21952 24389 27000 29791 32768 35937 39304]
i.b)  [  1.      3.375   8.     15.625  27.     42.875  64.     91.125 125.
 166.375]
ii)  [15626.    17579.375 19691.    21967.625 24416.    27042.875 29855.
 32859.125 36062.    39470.375]
iii)  138919.375
iv)  [125.00399994 132.58723543 140.32462364 148.21479346 156.25619988
 164.44717997 172.7859948  181.27086087 189.89997367 198.67152539]


__1b) Append b to a, reshape the appended array so that it is a 4x5, 2d array and store the results in a variable called m. Print m.__


In [3]:
# your code here
m = np.append(a,b)
m = m.reshape(4,5)
print(m)

[[1.56250e+04 1.75760e+04 1.96830e+04 2.19520e+04 2.43890e+04]
 [2.70000e+04 2.97910e+04 3.27680e+04 3.59370e+04 3.93040e+04]
 [1.00000e+00 3.37500e+00 8.00000e+00 1.56250e+01 2.70000e+01]
 [4.28750e+01 6.40000e+01 9.11250e+01 1.25000e+02 1.66375e+02]]


__1c) Extract the third and the fourth column of the m matrix. Store the resulting 4x2 matrix in a new variable called m2. Print m2.__


In [4]:
# your code here
m2 = m[:,2:4]
print(m2)

[[1.9683e+04 2.1952e+04]
 [3.2768e+04 3.5937e+04]
 [8.0000e+00 1.5625e+01]
 [9.1125e+01 1.2500e+02]]


__1d) Take the dot product of m2 and m store the results in a matrix called m3. Print m3.
Note that Dot product of two matrices A.B =A<sup>T</sup>B__

In [5]:
# your code here
m3 = np.dot(m.reshape(5,4), m2)
print(m3)

[[8.85635083e+08 9.77680259e+08]
 [1.36800900e+09 1.51024781e+09]
 [1.99526176e+09 2.20135731e+09]
 [6.73586984e+05 7.42912875e+05]
 [4.26185692e+06 4.70243712e+06]]


## Numpy conditions


__2a) Create a numpy array called 'f' where the values are cosine(x) for x from 0 to pi with 50 equally spaced values in f__
* Print f
* Use condition on the array and print an array that is True when f >= 1/2 and False when f < 1/2
* Create and print an array sequence that has only those values where f>= 1/2



In [6]:
# your code here
import math
f = np.arange(0,math.pi,math.pi/50)
f = np.cos(f)
print("f: ", f)

newarr = np.array([])
for each in f:
    if each >= (1/2):
        newarr = np.append(newarr, True)
    else: 
        newarr = np.append(newarr, False)
print("F Boolean: ", newarr)

new_list = [i for i in f if i >= 1/2]
print(new_list)

f:  [ 1.00000000e+00  9.98026728e-01  9.92114701e-01  9.82287251e-01
  9.68583161e-01  9.51056516e-01  9.29776486e-01  9.04827052e-01
  8.76306680e-01  8.44327926e-01  8.09016994e-01  7.70513243e-01
  7.28968627e-01  6.84547106e-01  6.37423990e-01  5.87785252e-01
  5.35826795e-01  4.81753674e-01  4.25779292e-01  3.68124553e-01
  3.09016994e-01  2.48689887e-01  1.87381315e-01  1.25333234e-01
  6.27905195e-02 -1.60812265e-16 -6.27905195e-02 -1.25333234e-01
 -1.87381315e-01 -2.48689887e-01 -3.09016994e-01 -3.68124553e-01
 -4.25779292e-01 -4.81753674e-01 -5.35826795e-01 -5.87785252e-01
 -6.37423990e-01 -6.84547106e-01 -7.28968627e-01 -7.70513243e-01
 -8.09016994e-01 -8.44327926e-01 -8.76306680e-01 -9.04827052e-01
 -9.29776486e-01 -9.51056516e-01 -9.68583161e-01 -9.82287251e-01
 -9.92114701e-01 -9.98026728e-01]
F Boolean:  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0.]
[1.0, 0.99802672

## NumPy and 2 Variable Prediction

__Let 'x' be the number of miles a person drives per day and 'y' be the dollars spent on buying car fuel (per day).__
  
__We have created 2 numpy arrays each of size 100 that represent x and y.  
x ( number of miles) ranges from 1 to 10 with a uniform noise of (0,1/2)  
y (money spent in dollars) will be from 1 to 20 with a uniform noise (0,1)__ 


In [7]:
# seed the random number generator with a fixed value
import numpy as np
np.random.seed(500)

x = np.linspace(1,10,100)+ np.random.uniform(low=0,high=.5,size=100) 
y = np.linspace(1,20,100)+ np.random.uniform(low=0,high=1,size=100)
print('x = ',x)
print('y = ',y)

x =  [ 1.34683976  1.12176759  1.51512398  1.55233174  1.40619168  1.65075498
  1.79399331  1.80243817  1.89844195  2.00100023  2.3344038   2.22424872
  2.24914511  2.36268477  2.49808849  2.8212704   2.68452475  2.68229427
  3.09511169  2.95703884  3.09047742  3.2544361   3.41541904  3.40886375
  3.50672677  3.74960644  3.64861355  3.7721462   3.56368566  4.01092701
  4.15630694  4.06088549  4.02517179  4.25169402  4.15897504  4.26835333
  4.32520644  4.48563164  4.78490721  4.84614839  4.96698768  5.18754259
  5.29582013  5.32097781  5.0674106   5.47601124  5.46852704  5.64537452
  5.49642807  5.89755027  5.68548923  5.76276141  5.94613234  6.18135713
  5.96522091  6.0275473   6.54290191  6.4991329   6.74003765  6.81809807
  6.50611821  6.91538752  7.01250925  6.89905417  7.31314433  7.20472297
  7.1043621   7.48199528  7.58957227  7.61744354  7.6991707   7.85436822
  8.03510784  7.80787781  8.22410224  7.99366248  8.40581097  8.28913792
  8.45971515  8.54227144  8.6906456   8.618565

__3a) Find Expected value of x and the expected value of y__

In [8]:
# your code here
print("EV of X: ",np.mean(x))
print("EV of Y: ",np.mean(y))

EV of X:  5.782532541587923
EV of Y:  11.012981683344968


__3b) Find variance of distributions of  x and  y__

In [9]:
# your code here
print("Variance of X: ",np.var(x))
print("Variance of Y: ",np.var(y))

Variance of X:  7.03332752947585
Variance of Y:  30.113903575509635


__3c) Find co-variance of x and y.__

In [10]:
# your code here
cov = np.mean(x * y) - np.mean(x) * np.mean(y)
print("CoVariance of X/Y: ",cov)

CoVariance of X/Y:  14.511166394475424


__3d) Assuming that number of dollars spent in car fuel is only dependant on the miles driven, by  a linear relationship.  
Write code that uses a linear predictor to calculate a predicted value of y for each x
i.e y_predicted = f(x) = y0+mx. (Do not use Machine learning libraries)__ 

In [11]:
# your code here

def predictor(x_0):
    m = cov/np.var(x)
    b = np.mean(y) - (cov * np.mean(x))/np.var(x)
    return m * x_0 + b

__3e) Predict y for each value in x, put the error into an array called y_error__

In [12]:
# your code here

y_predict = predictor(x)
y_error = (y_predict - y)**2
print(y_error)

[3.91074238e-02 3.90089068e-01 1.00602426e-02 6.28174407e-04
 4.34159397e-04 2.18246155e-01 6.00221492e-02 2.85588517e-01
 5.98611651e-02 4.58341762e-02 2.52102923e-01 7.71452229e-02
 3.86128331e-03 1.81289615e-01 8.67161417e-03 7.46587776e-01
 1.33978081e-02 9.95931872e-02 3.92702968e-01 1.61331949e-01
 2.12589019e-01 2.29961598e-01 1.30107881e-01 3.18226480e-02
 3.47417298e-01 1.18615933e-02 5.06305934e-03 8.42879328e-02
 5.51040190e-01 3.64155664e-02 1.26407037e-01 1.97742526e-02
 1.54484457e-01 3.22386643e-03 3.76118518e-01 6.44980460e-01
 6.02134420e-01 1.48256557e-02 4.06192410e-03 6.96083892e-02
 2.10937426e-01 1.52454276e-02 3.68125897e-01 4.03181563e-02
 4.36342204e-03 9.40673772e-02 1.09345421e-01 3.94107735e-03
 5.77405634e-01 4.56932708e-01 4.28612855e-01 7.95280194e-04
 7.40775594e-03 6.84928710e-02 5.32864845e-01 3.63682187e-01
 1.64543313e-01 2.91277455e-03 4.25053049e-04 8.15041286e-02
 5.48376537e-01 3.47024722e-01 1.87870128e-01 5.80371345e-01
 7.43982492e-04 1.060440

__3f) Write code that calculates the root mean square error(RMSE), that is root of average of y-error squared__


In [14]:
# your code here
rmse = np.sqrt(np.mean(y_error))
print(rmse)

0.41767772366856115


## Pandas Introduction


##  Reading File


In [15]:
# Load required modules
import pandas as pd
import numpy as np

#### Read the CSV file called 'data3.csv' into a dataframe called df. 
#### Data description
* File location: https://bcourses.berkeley.edu/files/74463396/download?download_frd=1
* Data source: http://www.fao.org/nr/water/aquastat/data/query/index.html?*lang=en
* Data, units:
* GDP, current USD (CPI adjusted)
* NRI, mm/yr
* Population density, inhab/km^2
* Total area of the country, 1000 ha = 10km^2
* Total Population, unit 1000 inhabitants


In [16]:
# your code here
df = pd.read_csv("data3.csv")

#### 4a ) Display the first 10 rows of the dataframe

In [17]:
# your code here
df.head(10)

Area  Area Id              Variable Name  Variable Id    Year  \
0  Argentina      9.0  Total area of the country       4100.0  1962.0   
1  Argentina      9.0  Total area of the country       4100.0  1967.0   
2  Argentina      9.0  Total area of the country       4100.0  1972.0   
3  Argentina      9.0  Total area of the country       4100.0  1977.0   
4  Argentina      9.0  Total area of the country       4100.0  1982.0   
5  Argentina      9.0  Total area of the country       4100.0  1987.0   
6  Argentina      9.0  Total area of the country       4100.0  1992.0   
7  Argentina      9.0  Total area of the country       4100.0  1997.0   
8  Argentina      9.0  Total area of the country       4100.0  2002.0   
9  Argentina      9.0  Total area of the country       4100.0  2007.0   

      Value Symbol  Other  
0  278040.0      E    NaN  
1  278040.0      E    NaN  
2  278040.0      E    NaN  
3  278040.0      E    NaN  
4  278040.0      E    NaN  
5  278040.0      E    NaN  
6  278040.0      E    NaN  
7  278040.0      E    NaN  
8  278040.0      E    NaN  
9  278040.0      E    NaN

#### 4b) Display the column names.

In [18]:
# your code here
df.columns

Index(['Area', 'Area Id', 'Variable Name', 'Variable Id', 'Year', 'Value',
       'Symbol', 'Other'],
      dtype='object')

#### 4c) Use iloc to display the first 3 rows and first 4 columns.

In [19]:
# your code here
df.iloc[0:3, 0:4]

Area  Area Id              Variable Name  Variable Id
0  Argentina      9.0  Total area of the country       4100.0
1  Argentina      9.0  Total area of the country       4100.0
2  Argentina      9.0  Total area of the country       4100.0



## Data Preprocessing

#### 5a ) Find all the rows that  have 'NaN' in the 'Symbol' column. Display first 5 rows.

##### Hint : You might have to use a condition (mask)

In [20]:
# your code here
nanVals = df[df["Symbol"].isnull()]
nanVals.head(5)

Area  Area Id Variable Name  Variable Id  Year  Value  \
390                    NaN      NaN           NaN          NaN   NaN    NaN   
391      E - External data      NaN           NaN          NaN   NaN    NaN   
392  I - AQUASTAT estimate      NaN           NaN          NaN   NaN    NaN   
393     K - Aggregate data      NaN           NaN          NaN   NaN    NaN   
394      L - Modelled data      NaN           NaN          NaN   NaN    NaN   

    Symbol  Other  
390    NaN    NaN  
391    NaN    NaN  
392    NaN    NaN  
393    NaN    NaN  
394    NaN    NaN

#### 5b )  Now, we will try to get rid of the NaN valued rows and columns. First, drop the column 'Other' which only has 'NaN' values. Then drop all other rows that have any column with a value 'NaN'.  Then display the last 5 rows of the dataframe.

In [21]:
# your code here
df = df.drop(columns='Other')
df = df.dropna()
df.tail()

Area  Area Id                  Variable Name  \
385  United States of America    231.0  National Rainfall Index (NRI)   
386  United States of America    231.0  National Rainfall Index (NRI)   
387  United States of America    231.0  National Rainfall Index (NRI)   
388  United States of America    231.0  National Rainfall Index (NRI)   
389  United States of America    231.0  National Rainfall Index (NRI)   

     Variable Id    Year   Value Symbol  
385       4472.0  1981.0   949.2      E  
386       4472.0  1984.0   974.6      E  
387       4472.0  1992.0  1020.0      E  
388       4472.0  1996.0  1005.0      E  
389       4472.0  2002.0   938.7      E




#### 6a) For our analysis we do not want all the columns in our dataframe. Lets  drop all the redundant columns/ features.   
#### **Drop columns**: **Area Id, Variable Id, Symbol**. Save the new dataframe as df1. Display the first 5 rows of the new dataframe.


In [22]:
# your code here
df1 = df.drop(columns=["Area Id", "Variable Id", "Symbol"])
df1.head()

Area              Variable Name    Year     Value
0  Argentina  Total area of the country  1962.0  278040.0
1  Argentina  Total area of the country  1967.0  278040.0
2  Argentina  Total area of the country  1972.0  278040.0
3  Argentina  Total area of the country  1977.0  278040.0
4  Argentina  Total area of the country  1982.0  278040.0

#### 6b) Display all the unique values in your new dataframe for columns: Area, Variable Name, Year.


In [24]:
# your code here


print("Area: ", set(df1["Area"]))
print()

print("Variable Name: ", set(df1["Variable Name"]))
print()

print("Year: ", set(df1["Year"]))

Area:  {'Argentina', 'Australia', 'Sweden', 'Germany', 'Ireland', 'United States of America', 'Iceland'}

Variable Name:  {'Total population', 'Population density', 'Total area of the country', 'National Rainfall Index (NRI)', 'Gross Domestic Product (GDP)'}

Year:  {1962.0, 1963.0, 1964.0, 1965.0, 1967.0, 1969.0, 1970.0, 1971.0, 1972.0, 1973.0, 1974.0, 1975.0, 1977.0, 1978.0, 1979.0, 1981.0, 1982.0, 1983.0, 1984.0, 1985.0, 1986.0, 1987.0, 1988.0, 1990.0, 1991.0, 1992.0, 1993.0, 1995.0, 1996.0, 1997.0, 1998.0, 2000.0, 2001.0, 2002.0, 2007.0, 2012.0, 2014.0, 2015.0}


__6c) Convert the year column to pandas datetime. Convert the 'Year' column float values to pandas datetime objects, where each year is represented as the first day of that year. Also display the column and datatype for 'Year' after conversion.
For eg: 1962.0 will be represented as 1962-01-01¶__


In [25]:
df1["Year"] = pd.to_datetime(df1["Year"].astype(int), format="%Y")
df1.head()

Area              Variable Name       Year     Value
0  Argentina  Total area of the country 1962-01-01  278040.0
1  Argentina  Total area of the country 1967-01-01  278040.0
2  Argentina  Total area of the country 1972-01-01  278040.0
3  Argentina  Total area of the country 1977-01-01  278040.0
4  Argentina  Total area of the country 1982-01-01  278040.0

## Extract specific statistics from the preprocessed data:

#### 7a)  Create a dataframe 'dftemp' to store rows where Area is 'Iceland'. Display the dataframe.

In [26]:
# your code here
dftemp = df1[df1["Area"] == "Iceland"]
dftemp.head()

Area              Variable Name       Year    Value
166  Iceland  Total area of the country 1962-01-01  10300.0
167  Iceland  Total area of the country 1967-01-01  10300.0
168  Iceland  Total area of the country 1972-01-01  10300.0
169  Iceland  Total area of the country 1977-01-01  10300.0
170  Iceland  Total area of the country 1982-01-01  10300.0

#### 7b) Print the years when the National Rainfall Index (NRI) was greater than 900 and less than 950 in Iceland. Use the dataframe you created in the previous question 'dftemp'. 

In [35]:
# your code here
n_r_i = dftemp[dftemp["Variable Name"] == "National Rainfall Index (NRI)"]
yearsTemp = [n_r_i['Year'][x].year for x in n_r_i.index if n_r_i['Value'][x] > 900 and n_r_i['Value'][x] < 950]
print("Years of Max NRI: ", yearsTemp)

Years of Max NRI:  [1981, 1998]


## US statistics: 


#### 8a) Create a new DataFrame called **`df_usa`** that only contains values where 'Area' is equal to 'United States of America'. Set the indices to be the 'Year' column    ( Use .set_index( ) ). Display the dataframe head.

In [36]:
# your code here
df_usa = df1[df1["Area"] == "United States of America"].set_index("Year")
df_usa.head()

Area              Variable Name     Value
Year                                                                     
1962-01-01  United States of America  Total area of the country  962909.0
1967-01-01  United States of America  Total area of the country  962909.0
1972-01-01  United States of America  Total area of the country  962909.0
1977-01-01  United States of America  Total area of the country  962909.0
1982-01-01  United States of America  Total area of the country  962909.0


#### 8b) Pivot the DataFrame so that the unique values in the column 'Variable Name' becomes the columns. The DataFrame values should be the ones in the the 'Value' column. Save it in df_usa. Display the dataframe head.

In [37]:
# your code here
dfPivoted = df_usa.pivot(index=df_usa.index, columns='Variable Name')['Value']
df_usa = df_usa.drop(columns=["Variable Name", "Value"])
df_usa[dfPivoted.columns] = dfPivoted
df_usa.head()

Area  Gross Domestic Product (GDP)  \
Year                                                                 
1962-01-01  United States of America                  6.050000e+11   
1967-01-01  United States of America                  8.620000e+11   
1972-01-01  United States of America                  1.280000e+12   
1977-01-01  United States of America                  2.090000e+12   
1982-01-01  United States of America                  3.340000e+12   

            National Rainfall Index (NRI)  Population density  \
Year                                                            
1962-01-01                            NaN               19.93   
1967-01-01                            NaN               21.16   
1972-01-01                            NaN               22.14   
1977-01-01                            NaN               23.17   
1982-01-01                            NaN               24.30   

            Total area of the country  Total population  
Year                                                     
1962-01-01                   962909.0          191861.0  
1967-01-01                   962909.0          203713.0  
1972-01-01                   962909.0          213220.0  
1977-01-01                   962909.0          223091.0  
1982-01-01                   962909.0          233954.0

#### 8c) Rename new columns to  ['GDP','NRI','PD','Area','Population'] and display the head.


In [38]:
# your code here
df_usa = df_usa.rename({
    "Area": "Country",
    "Gross Domestic Product (GDP)": "GDP",
    "National Rainfall Index (NRI)": "NRI",
    "Population density": "PD",
    "Total area of the country": "Area",
    "Total population": "Population"
}, axis="columns")
df_usa.head()

Country           GDP  NRI     PD      Area  \
Year                                                                       
1962-01-01  United States of America  6.050000e+11  NaN  19.93  962909.0   
1967-01-01  United States of America  8.620000e+11  NaN  21.16  962909.0   
1972-01-01  United States of America  1.280000e+12  NaN  22.14  962909.0   
1977-01-01  United States of America  2.090000e+12  NaN  23.17  962909.0   
1982-01-01  United States of America  3.340000e+12  NaN  24.30  962909.0   

            Population  
Year                    
1962-01-01    191861.0  
1967-01-01    203713.0  
1972-01-01    213220.0  
1977-01-01    223091.0  
1982-01-01    233954.0

#### 8d) Replace all 'Nan' values in df_usa with 0. Display the head of the dataframe.

In [39]:
# your code here
df_usa = df_usa.fillna(value=0)
df_usa.head()

Country           GDP  NRI     PD      Area  \
Year                                                                       
1962-01-01  United States of America  6.050000e+11  0.0  19.93  962909.0   
1967-01-01  United States of America  8.620000e+11  0.0  21.16  962909.0   
1972-01-01  United States of America  1.280000e+12  0.0  22.14  962909.0   
1977-01-01  United States of America  2.090000e+12  0.0  23.17  962909.0   
1982-01-01  United States of America  3.340000e+12  0.0  24.30  962909.0   

            Population  
Year                    
1962-01-01    191861.0  
1967-01-01    203713.0  
1972-01-01    213220.0  
1977-01-01    223091.0  
1982-01-01    233954.0

## Note: Use df_usa

#### 9a) Multiply the 'Area' column for all countries by 10 (so instead of 1000 ha, the unit becomes 100 ha = 1km^2). Display the dataframe head.


In [40]:
# your code here
df_usa["Area"] *= 10
df_usa.head()

Country           GDP  NRI     PD       Area  \
Year                                                                        
1962-01-01  United States of America  6.050000e+11  0.0  19.93  9629090.0   
1967-01-01  United States of America  8.620000e+11  0.0  21.16  9629090.0   
1972-01-01  United States of America  1.280000e+12  0.0  22.14  9629090.0   
1977-01-01  United States of America  2.090000e+12  0.0  23.17  9629090.0   
1982-01-01  United States of America  3.340000e+12  0.0  24.30  9629090.0   

            Population  
Year                    
1962-01-01    191861.0  
1967-01-01    203713.0  
1972-01-01    213220.0  
1977-01-01    223091.0  
1982-01-01    233954.0


#### 9b) Create a new column in df_usa called 'GDP/capita' and populate it with the calculated GDP per capita. Round the results to two decimal points. Display the dataframe head.
GDP per capita = (GDP / Population)

In [41]:
# your code here
df_usa["GDP/capita"] = (df_usa["GDP"]/df_usa["Population"]).round(2)
df_usa.head()

Country           GDP  NRI     PD       Area  \
Year                                                                        
1962-01-01  United States of America  6.050000e+11  0.0  19.93  9629090.0   
1967-01-01  United States of America  8.620000e+11  0.0  21.16  9629090.0   
1972-01-01  United States of America  1.280000e+12  0.0  22.14  9629090.0   
1977-01-01  United States of America  2.090000e+12  0.0  23.17  9629090.0   
1982-01-01  United States of America  3.340000e+12  0.0  24.30  9629090.0   

            Population   GDP/capita  
Year                                 
1962-01-01    191861.0   3153324.54  
1967-01-01    203713.0   4231443.26  
1972-01-01    213220.0   6003189.19  
1977-01-01    223091.0   9368374.34  
1982-01-01    233954.0  14276310.73


#### 9c) Find the maximum value of the 'NRI' column in the US (using pandas methods). What year does the max value occur? Display the values.

In [42]:
# your code here
max_NRI = df_usa.max(axis=0)['NRI']
print("Maximum NRI: ", max_NRI)

yr = df_usa[df_usa["NRI"] == max_NRI]
print("Year of Max NRI: ", str(yr.index.values[0])[0:4])

Maximum NRI:  1020.0
Year of Max NRI:  1992
